namespace SubstationTracker.Application.Features.Users.OtherFeatures.Admins.Queries.GetAdminEmailAddresses;

public class GetAdminEmailAddressesQueryRequestValidator : AbstractValidator<GetAdminEmailAddressesQueryRequest>
{
}