//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubstationTracker.Application.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_tr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_tr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubstationTracker.Application.Resources.Languages.Lang.tr-TR", typeof(Lang_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envanter kaydı başarıyla oluşturuldu..
        /// </summary>
        internal static string InventoryDataIsCreated {
            get {
                return ResourceManager.GetString("InventoryDataIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envanter kaydı oluşturulamadı..
        /// </summary>
        internal static string InventoryDataIsNotCreated {
            get {
                return ResourceManager.GetString("InventoryDataIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün başarıyla oluşturuldu..
        /// </summary>
        internal static string ProductIsCreated {
            get {
                return ResourceManager.GetString("ProductIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün başarıyla silindi..
        /// </summary>
        internal static string ProductIsDeleted {
            get {
                return ResourceManager.GetString("ProductIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün oluşturulamadı..
        /// </summary>
        internal static string ProductIsNotCreated {
            get {
                return ResourceManager.GetString("ProductIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün silinemedi..
        /// </summary>
        internal static string ProductIsNotDeleted {
            get {
                return ResourceManager.GetString("ProductIsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bulunamadı..
        /// </summary>
        internal static string ProductIsNotFound {
            get {
                return ResourceManager.GetString("ProductIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün güncellenemedi..
        /// </summary>
        internal static string ProductIsNotUpdated {
            get {
                return ResourceManager.GetString("ProductIsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün başarıyla güncellendi..
        /// </summary>
        internal static string ProductIsUpdated {
            get {
                return ResourceManager.GetString("ProductIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün adı zaten var..
        /// </summary>
        internal static string ProductNameIsAlreadyExist {
            get {
                return ResourceManager.GetString("ProductNameIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürüne ait sektörler listelendi..
        /// </summary>
        internal static string ProductSectorsAreListed {
            get {
                return ResourceManager.GetString("ProductSectorsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün ait sektörler bulunamadı..
        /// </summary>
        internal static string ProductSectorsAreNotFound {
            get {
                return ResourceManager.GetString("ProductSectorsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünün sektörleri güncellenemedi..
        /// </summary>
        internal static string ProductSectorsAreNotUpdated {
            get {
                return ResourceManager.GetString("ProductSectorsAreNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünün sektörleri başarıyla güncellendi..
        /// </summary>
        internal static string ProductSectorsAreUpdated {
            get {
                return ResourceManager.GetString("ProductSectorsAreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenileme tokeni oluşturulamadı..
        /// </summary>
        internal static string RefreshTokenIsNotGenerated {
            get {
                return ResourceManager.GetString("RefreshTokenIsNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kullanıcı, şubeye başarıyla eklendi..
        /// </summary>
        internal static string ResponsibleUserIsAddedToSubstation {
            get {
                return ResourceManager.GetString("ResponsibleUserIsAddedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu kullanıcı, şubeye eklenemedi..
        /// </summary>
        internal static string ResponsibleUserIsNotAddedToSubstation {
            get {
                return ResourceManager.GetString("ResponsibleUserIsNotAddedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller, seçilen kullanıcıya başarıyla eklendi..
        /// </summary>
        internal static string RolesAreAddedToTheUser {
            get {
                return ResourceManager.GetString("RolesAreAddedToTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller, seçilen kullanıcıya eklenemedi..
        /// </summary>
        internal static string RolesAreNotAddedToTheUser {
            get {
                return ResourceManager.GetString("RolesAreNotAddedToTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör, şubeye başarıyla eklendi..
        /// </summary>
        internal static string SectorIsAddedToSubstation {
            get {
                return ResourceManager.GetString("SectorIsAddedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör getirildi..
        /// </summary>
        internal static string SectorIsBrought {
            get {
                return ResourceManager.GetString("SectorIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör başarıyla silindi..
        /// </summary>
        internal static string SectorIsDeleted {
            get {
                return ResourceManager.GetString("SectorIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör, şubeye eklenemedi..
        /// </summary>
        internal static string SectorIsNotAddedToSubstation {
            get {
                return ResourceManager.GetString("SectorIsNotAddedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör silinemedi..
        /// </summary>
        internal static string SectorIsNotDeleted {
            get {
                return ResourceManager.GetString("SectorIsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör bulunamadı..
        /// </summary>
        internal static string SectorIsNotFound {
            get {
                return ResourceManager.GetString("SectorIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör güncellenemedi..
        /// </summary>
        internal static string SectorIsNotUpdated {
            get {
                return ResourceManager.GetString("SectorIsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör başarıyla güncellendi..
        /// </summary>
        internal static string SectorIsUpdated {
            get {
                return ResourceManager.GetString("SectorIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör adı zaten var. ({0}).
        /// </summary>
        internal static string SectorNameIsAlreadyExist {
            get {
                return ResourceManager.GetString("SectorNameIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler, ürüne başarıyla eklendi..
        /// </summary>
        internal static string SectorsAreAddedToProduct {
            get {
                return ResourceManager.GetString("SectorsAreAddedToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler başarıyla oluşturuldu..
        /// </summary>
        internal static string SectorsAreCreated {
            get {
                return ResourceManager.GetString("SectorsAreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler listelendi..
        /// </summary>
        internal static string SectorsAreListed {
            get {
                return ResourceManager.GetString("SectorsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler, ürüne eklenemedi..
        /// </summary>
        internal static string SectorsAreNotAddedToProduct {
            get {
                return ResourceManager.GetString("SectorsAreNotAddedToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler oluşturulamadı..
        /// </summary>
        internal static string SectorsAreNotCreated {
            get {
                return ResourceManager.GetString("SectorsAreNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler bulunamadı..
        /// </summary>
        internal static string SectorsAreNotFound {
            get {
                return ResourceManager.GetString("SectorsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubenin zaten bir sorumlusu var..
        /// </summary>
        internal static string SubstationIsAlreadyHaveAResponsibleUser {
            get {
                return ResourceManager.GetString("SubstationIsAlreadyHaveAResponsibleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube başarıyla getirildi..
        /// </summary>
        internal static string SubstationIsBrought {
            get {
                return ResourceManager.GetString("SubstationIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube başarıyla oluşturuldu..
        /// </summary>
        internal static string SubstationIsCreated {
            get {
                return ResourceManager.GetString("SubstationIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube başarıyla silindi..
        /// </summary>
        internal static string SubstationIsDeleted {
            get {
                return ResourceManager.GetString("SubstationIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube oluşturulamadı..
        /// </summary>
        internal static string SubstationIsNotCreated {
            get {
                return ResourceManager.GetString("SubstationIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube silinemedi..
        /// </summary>
        internal static string SubstationIsNotDeleted {
            get {
                return ResourceManager.GetString("SubstationIsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube bulunamadı..
        /// </summary>
        internal static string SubstationIsNotFound {
            get {
                return ResourceManager.GetString("SubstationIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube güncellenemedi..
        /// </summary>
        internal static string SubstationIsNotUpdated {
            get {
                return ResourceManager.GetString("SubstationIsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube başarıyla güncellendi..
        /// </summary>
        internal static string SubstationIsUpdated {
            get {
                return ResourceManager.GetString("SubstationIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube hareketi başarıyla oluşturuldu..
        /// </summary>
        internal static string SubstationMovementIsCreated {
            get {
                return ResourceManager.GetString("SubstationMovementIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube hareketi oluşturulamadı..
        /// </summary>
        internal static string SubstationMovementIsNotCreated {
            get {
                return ResourceManager.GetString("SubstationMovementIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube hareketleri listelendi..
        /// </summary>
        internal static string SubstationMovementsAreListed {
            get {
                return ResourceManager.GetString("SubstationMovementsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube hareketleri bulunamadı..
        /// </summary>
        internal static string SubstationMovementsAreNotFound {
            get {
                return ResourceManager.GetString("SubstationMovementsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube adı zaten var..
        /// </summary>
        internal static string SubstationNameIsAlreadyExist {
            get {
                return ResourceManager.GetString("SubstationNameIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeler başarıyla listelendi..
        /// </summary>
        internal static string SubstationsAreListed {
            get {
                return ResourceManager.GetString("SubstationsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeler bulunamadı..
        /// </summary>
        internal static string SubstationsAreNotFound {
            get {
                return ResourceManager.GetString("SubstationsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubenin sektörleri bulunamadı..
        /// </summary>
        internal static string SubstationSectorsAreNotFound {
            get {
                return ResourceManager.GetString("SubstationSectorsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün ile sektör zaten ilişkili..
        /// </summary>
        internal static string TheProductAndSectorAlreadyRelated {
            get {
                return ResourceManager.GetString("TheProductAndSectorAlreadyRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör isimleri zaten var. ({0}).
        /// </summary>
        internal static string TheSectorNamesAreAlreadyExist {
            get {
                return ResourceManager.GetString("TheSectorNamesAreAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube, zaten bu sektöre sahip. ({0}).
        /// </summary>
        internal static string TheSubstationIsAlreadyHaveTheSector {
            get {
                return ResourceManager.GetString("TheSubstationIsAlreadyHaveTheSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu şube, sizin sorumluluğunuzda değil..
        /// </summary>
        internal static string TheSubstationIsNotYourResponsibility {
            get {
                return ResourceManager.GetString("TheSubstationIsNotYourResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) kullanıcısı zaten ({1}) şubesinden sorumlu..
        /// </summary>
        internal static string TheUserIsAlreadyResposibleFromSubstation {
            get {
                return ResourceManager.GetString("TheUserIsAlreadyResposibleFromSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürün, bu şubede yok..
        /// </summary>
        internal static string ThisProductIsNotAvailableAtThisSubstation {
            get {
                return ResourceManager.GetString("ThisProductIsNotAvailableAtThisSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı zaten bu rollere sahip..
        /// </summary>
        internal static string UserIsAlreadyHaveTheRoles {
            get {
                return ResourceManager.GetString("UserIsAlreadyHaveTheRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı belirtilen şubeye başarıyla atandı..
        /// </summary>
        internal static string UserIsAssignedToSubstation {
            get {
                return ResourceManager.GetString("UserIsAssignedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı belirtilen şubeye atanamadı..
        /// </summary>
        internal static string UserIsNotAssignedToSubstation {
            get {
                return ResourceManager.GetString("UserIsNotAssignedToSubstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı logu başarıyla oluşturuldu..
        /// </summary>
        internal static string UserLogIsCreated {
            get {
                return ResourceManager.GetString("UserLogIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalnızca bir tane sorumlu kullanıcı seçebilirsiniz..
        /// </summary>
        internal static string YouCanOnlyChooseOneResponsibleUser {
            get {
                return ResourceManager.GetString("YouCanOnlyChooseOneResponsibleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalnızca bir tane sektör seçebilirsiniz..
        /// </summary>
        internal static string YouCanOnlyChooseOneSector {
            get {
                return ResourceManager.GetString("YouCanOnlyChooseOneSector", resourceCulture);
            }
        }
    }
}
